### ISSUE TITLE
Build process stop with missing file

### ISSUE THREAD

**Issue by WalterLx** [mangopi-sbc/Tina-Linux#1]
https://fossies.org/linux/misc/lz4-1.9.2.tar.gz

Just a "Fossies" guess: The requested file or information you originally searched for under
  /linux/misc/lz4-1.9.2.tar.gz
may now be available under
  [/linux/misc/lz4-1.9.3.tar.gz](https://fossies.org/linux/misc/lz4-1.9.3.tar.gz)

**Comment by mangobuge** [comment]
I will fix it.  
I forgot the dl folder.

**Comment by WalterLx** [comment]
There must be a misunderstanding.
Build step tries to download https://fossies.org/linux/misc/lz4-1.9.2.tar.gz but this is not available anymore. 
It should be https://fossies.org/linux/misc/lz4-1.9.3.tar.gz
