### ISSUE TITLE
Tina linux bricks on the logo

### ISSUE THREAD

**Issue by EmilioEstefan** [mangopi-sbc/Tina-Linux#10]
when i try to start tina for first time, it bricks on the logo, and i can't use it
![Issue](https://user-images.githubusercontent.com/80013699/195476326-521e473d-4ac8-4e5c-97c3-a85585e19a7a.PNG)
e it bricks on the logo

**Comment by EmilioEstefan** [comment]
I have solved it! this is an headless linux system, you need to connect your mango pi to your computer, so after you install ADB tools for your windows or other system, open a cmd on the path of ADB tools and run this --> adb shell
So it's all, enjoy your MANGO PI !
![TINA LINUX](https://user-images.githubusercontent.com/80013699/195495337-f2c668b2-bfa6-43f5-a13a-cd729cf0b7a7.PNG)

**Comment by mangobuge** [comment]
let's play ArmBian on MangoPi MQ-Quad or Pro :)

**Comment by vladimir-dudnik** [comment]
yes, Armbian work well on MangoPi MQ Pro, except it does not init CPU with riscv vector extensions
