### ISSUE TITLE
为什么我编译出来的固件烧录SD卡，sd插到mangopi-MQ上不能启动

### ISSUE THREAD

**Issue by 37ge** [mangopi-sbc/Tina-Linux#2]
![image](https://user-images.githubusercontent.com/49938697/183284823-4d5948d9-6e01-4ab1-b7a5-a46b6e8a6946.png)
![image](https://user-images.githubusercontent.com/49938697/183284841-503fe9ef-ee98-4334-9dd3-4322ea618076.png)

**Comment by mangobuge** [comment]
之前的确有问题，请更新到最新的测试
