### ISSUE TITLE
make报错

### ISSUE THREAD

**Issue by lztmfx** [mangopi-sbc/Tina-Linux#4]
ERROR: please fix package/allwinner/eyesee-mpp/dragonboard/Makefile - see logs/package/allwinner/eyesee-mpp/dragonboard/dump.txt for details
#dump.txt文件内容: Makefile:52: *** fatal error! sun20iw1p1 is not support by eyesee-mpp!.  Stop.

ERROR: please fix package/allwinner/eyesee-mpp/middleware/Makefile - see logs/package/allwinner/eyesee-mpp/middleware/dump.txt for details
#dump.txt文件内容: Makefile:42: *** fatal error! sun20iw1p1 is not support by eyesee-mpp!.  Stop.

ERROR: please fix package/libs/libgpu/Makefile - see logs/package/libs/libgpu/dump.txt for details
#dump.txt文件内容: Makefile:75: *** Invalid TARGET_ARCH riscv.  Stop.
ERROR: please fix package/libs/libgpu-opencl/Makefile - see logs/package/libs/libgpu-opencl/dump.txt for details
#dump.txt文件内容: Makefile:63: *** Invalid TARGET_ARCH riscv.  Stop.

lunch如下:
Which would you like? [Default f133_mq_r]: 1
============================================
TINA_BUILD_TOP=/home/lzt/Tina-Linux
TINA_TARGET_ARCH=riscv
TARGET_PRODUCT=d1_mq_pro
TARGET_PLATFORM=d1
TARGET_BOARD=d1-mq_pro
TARGET_PLAN=mq_pro
TARGET_BUILD_VARIANT=tina
TARGET_BUILD_TYPE=release
TARGET_KERNEL_VERSION=5.4
TARGET_UBOOT=u-boot-2018
TARGET_CHIP=sun20iw1p1
============================================

**Comment by mangobuge** [comment]
这几个包不适用于f133平台，所以报错，无需理会
